version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Caminho para o diretório que contém o Dockerfile do frontend
      dockerfile: Dockerfile  # Nome do Dockerfile (opcional, caso seja apenas "Dockerfile" no diretório)
    container_name: frontend  # Nome do container do frontend
    ports:
      - "3000:80"  # Mapeia a porta 3000 do host para a porta 80 do container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
