version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Caminho para o diretório que contém o Dockerfile do frontend
      dockerfile: Dockerfile  # Nome do Dockerfile (opcional, caso seja apenas "Dockerfile" no diretório)
    container_name: frontend  # Nome do container do frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
