name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verificar a instalação do Docker Compose

      - name: Build Docker image
        run: docker build -t vsantosmt/ad-iv-centenario-scale-frontend:1.0 ./frontend

      - name: Push Docker image
        run: docker push vsantosmt/ad-iv-centenario-scale-frontend:1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Docker image
        run: docker run -d -p 80:80 vsantosmt/ad-iv-centenario-scale-frontend:1.0
